server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: mall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hahow_mall
    username: root
    password: root_password
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
